version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/example"
      - "/{{ cookiecutter.project_slug }}"
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "org.jetbrains.kotlin:*"
      kotlinx:
        patterns:
          - "org.jetbrains.kotlinx*"
      compose:
        patterns:
          - "org.jetbrains.compose*"
          - "org.jetbrains.androidx.*"
      android:
        patterns:
          - "com.android*"
      androidx:
        patterns:
          - "androidx.*"
      kroegerama:
        patterns:
          - "com.kroegerama*"
      other:
        patterns:
          - "*"
